title: 05m4n-Blog
description: "Programming,Cybersecurity"
author:
  name: "05N4N"
  email: "egaro.148@gmail.com"
  url: "https://o5m4n.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
      
      
 # Site Author
author:
  name             : "05M4N"
  avatar           : "/assets/images/20430659.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "A passionate full stack developer, GNU\\LINUX lover, and Cyeber-Security enthusiast.."
  location         : "Mexico"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/O5M4N" # url: "https://github.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-gitlab" #<i class="fab fa-gitlab"></i> 
      url: "https://gitlab.com/O5M4N" # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eorg/"     

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "05m4n"
year : "2021"
