title: 05m4n-Blog
description: "Programming,Cybersecurity"
author:
  name: "05N4N"
  email: "egaro.148@gmail.com"
  url: "https://o5m4n.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "05m4n"
year : "2021"
